# Generated by Django 2.2.7 on 2020-01-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='defaultpp.jpg', null=True, upload_to='profile_photo'),
        ),
    ]
