# Generated by Django 2.2.7 on 2019-12-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191212_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='additional_data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_photo'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
