# Generated by Django 2.2.7 on 2019-12-12 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191212_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='additional_data',
            field=models.CharField(blank=True, default='none', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='none', max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be valid', regex='^\\+?1?\\d{9,10}$')]),
        ),
    ]
