# Generated by Django 2.2.7 on 2020-01-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200108_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='ans',
            new_name='time_stamp',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
