# Generated by Django 3.0.2 on 2020-02-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200108_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile_photo'),
        ),
    ]
